#!/bin/bash
#SBATCH --partition=student
#SBATCH --account=student
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=1G
#SBATCH --job-name="DelayResolvedStoch"
#SBATCH --gres=gpu:1
#SBATCH -t 2-6:00
export PATH="/home/stud-lscholz/.conda/envs/Tensorflow2/bin:$PATH"
for delay in 0 2 4 6 8 10
do
	  nohup python3 train.py --algorithm IS --stochastic False --verbose True --delay $delay &
	    nohup python3 train.py --algorithm normal --stochastic False --verbose True --delay $delay
	      nohup python3 train.py --algorithm delay --stochastic False --verbose True --delay $delay
done
